config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
  	resources :comments
  end
  root "posts#index"
  get '/about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: {minimum: 5}
	validates :content,  presence: true
	belongs_to :user
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.build(params[:comment].permit(:name, :content))
		@comment.user = current_user
		@comment.save
		redirect_to post_path(@post)
	end
	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	def index
		@posts = Post.all.order('created_at DESC')
	end

	def new
		@post = current_user.posts.build
	end

	def show
		@post = Post.find(params[:id])
	end

	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if @post.update(params[:post].permit(:title, :content, :image))
			redirect_to @post
		else
			render 'edit'
		end
	end
	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to root_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :content, :image)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
.comment.clearfix
	.comment_content
		%p.comment_name
			%strong= comment.user.email
		%p.comment_body= comment.content
		%p.comment_time
			= time_ago_in_words(comment.created_at)
			Ago
	- if comment.user == current_user
		%p= link_to 'Delete', [comment.post, comment], method: :delete, class: "button", data: { confirm: 'Are you sure?'}

app/views/comments/_form.html.haml
= form_for([@post, @post.comments.build]) do |f|

	= f.label :content
	%br
	= f.text_area :content
	%br
	%br
	=f.submit

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'%>
  </head>

  <body>
  	<div id="sidebar">
		<div id="logo">
			<%= link_to root_path do %>
				<%= image_tag "logo.svg" %>
			<% end %>
		</div>

		<ul>
			<li class="category">Website</li>
			<li><%= link_to "Blog", root_path %></li>
			<li><%= link_to "Calendar", root_path %></li>
			<li><%= link_to "About", about_path%></li>
		</ul>

		<ul>
			<li class="category">Social</li>
			<li><a href="https://www.facebook.com/kittichote.kamalapirat">Facebook</a></li>
			<li><a href="https://github.com/kitticode">Github</a></li>
			<li><a href="mailto:hey@mackenziechild.me">Email</a></li>
		</ul>
		<% if !user_signed_in? %>
			<p class="sign_in">Admin Login</p>
		<% end %>

	</div>
		<div id="main_content">
			<div id="header">
				<% if current_page?(root_path) %>
					<p>All Posts</p>
				<% elsif current_page?(about_path) %>
					<p>About</p>
				<% else %>
					<%= link_to "Back to All Posts", root_path %>
				<% end %>
				<div class="buttons">
					<button class="button"><%= link_to 'New Post', new_post_path %></button>
				</div>
				<% if user_signed_in? %>
					<div class="buttons">
						<button class="button"><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></button>
					</div>
				<% else %>
					<div class="buttons">
						<button class="button"><%= link_to 'Sign Up', new_user_registration_path %></button>
						<button class="button"><%= link_to 'Sign In', new_user_session_path %></button>
					</div>
				<% end %>
			</div>
			<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert")%>
			<%end%>
			<%= yield %>
		</div>
  </body>

</html>

app/views/pages/about.html.haml
#page_wrapper
	#profile_image
		= image_tag "profile.jpeg"

	#content
		%h1 Hey, I'm Mackenzie Child
		%p Welcome to week 2 of my 12 Web Apps in 12 Weeks Challenge.
		%p This week I built a blog in Rails 4. You're actually on the demo application right now. Cool stuff, right!.
		%p 
			If you'd like to follow along as I learn more Ruby on Rails, find me on Twitter 
			/ %a{ href: "http://twitter.com/mackenziechild"}
			/ 	@MackenzieChild
			/ or on the web at 
			/ %a{href: "http://mackenziechild.me">mackenziechild.me}
			/ , and get my posts and exclusive content in your inbox by signing up for my newsletter 

app/views/posts/_form.html.haml
= form_for @post, html: {multipart: true} do |f|
	-if @post.errors.any?
		#errors
			#errors
				%h2
					= pluralize(@post.errors.count, "error") 
					prevented this post from saving
				%ul
				- @post.errors.full_messages.each do |msg|
					%li= msg

	= f.label :image
	%br
	%br
	= f.file_field :image
	%br
	%br
	= f.label :title 
	%br
	= f.text_field :title
	%br
	= f.label :content
	%br
	= f.text_area :content
	%br
	%br
	= f.submit

app/views/posts/edit.html.haml
#page_wrapper
	%h1 
		Edit Post
	= render 'form'

app/views/posts/index.html.haml
- @posts.each do |post|
	.post_wrapper
		%h2{class: "title"}
			= link_to post.title, post
		%p{class: "date"}
			= post.created_at.strftime("%B, %d, %Y")
		created by
		%b= post.user.email
		- if post.user == current_user
			%br
			= link_to 'Edit', edit_post_path(post)
			|
			= link_to 'Delete', post_path(post), method: 'delete'
		.image
			=image_tag post.image.url(:thumb)

app/views/posts/new.html.haml
#page_wrapper
	%h1 
		New Post
	=form_for :post, url: posts_path do |f|
		- if @post.errors.any?
			#errors
				%h2
					= pluralize(@post.errors.count, "error") 
					prevented this post from saving
				%ul
				- @post.errors.full_messages.each do |msg|
					%li= msg

		%p
			= f.label :title 
			%br
			= f.text_field :title
		%p
			= f.label :content
			%br
			= f.text_area :content
		%p
			= f.submit

app/views/posts/show.html.haml
#post_content
	=image_tag @post.image.url(:medium)
	%h1{class: "title"}
		=@post.title
	submited
	%b{class: "date"}
		= time_ago_in_words(@post.created_at)
	ago 
	- if @post.user == current_user
		|
		= link_to 'Edit', edit_post_path(@post)
		|
		= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: "Are you sure?"}
		%p{class: "body"} 
		=@post.content

	
	#comments
		%h2
			= @post.comments.count
			Comments
		= render @post.comments

		%h3 Add a comment:
		= render "comments/form"